from tkinter import *
import tkinter as tk

def header_grid_random(window):
    # -----------------------------------GRID-----------------------------
    img_random = PhotoImage(file="")
    sm_img_rd = img_random.subsample(5,5)

    img_rd1  = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd2  = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd3  = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd4  = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd5  = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd6  = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd7  = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd8  = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd9  = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd10 = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd11 = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd12 = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd13 = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd14 = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd15 = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd16 = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd17 = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd18 = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    img_rd19 = Label(window, image= sm_img_rd, bg="#00ff00", width="15")
    img_rd20 = Label(window, image= sm_img_rd, bg="#0000ff", width="15")
    

    img_rd1.grid (row=0, column=0)
    img_rd2.grid (row=0, column=1)
    img_rd3.grid (row=0, column=2)
    img_rd4.grid (row=0, column=3)
    img_rd5.grid (row=0, column=4)
    img_rd6.grid (row=0, column=5)
    img_rd7.grid (row=0, column=6)
    img_rd8.grid (row=0, column=7)
    img_rd9.grid (row=0, column=8)
    img_rd10.grid(row=0, column=9)
    img_rd11.grid(row=0, column=10)
    img_rd12.grid(row=0, column=11)
    img_rd13.grid(row=0, column=12)
    img_rd14.grid(row=0, column=13)
    img_rd15.grid(row=0, column=14)
    img_rd16.grid(row=0, column=15)
    img_rd17.grid(row=0, column=16)
    img_rd18.grid(row=0, column=17)
    img_rd19.grid(row=0, column=18)
    img_rd20.grid(row=0, column=19)